version: 2.1

jobs:
  build:
    macos:
      xcode: "16.1"
    steps:
      - checkout
      - run:
          name: Build
          command: xcodebuild -project CoNotebook.xcodeproj -scheme CoNotebook -sdk iphonesimulator clean build

  deploy_to_testflight:
    macos:
      xcode: "16.1"
    steps:
      - checkout
      - run:
          name: Configure provisioning profile
          command: |
            echo $MOBILEPROVISION_BASE64 | base64 --decode > provisionning_profile_app_store_conotebook.mobileprovision
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            mv provisionning_profile_app_store_conotebook.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      - run:
          name: Upload to testflight
          command: fastlane beta

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_testflight:
          requires:
            - build
          filters:
            branches:
              only: release

