version: 2.1
jobs:
  build:
    macos:
      xcode: "16.1"
    steps:
      - checkout
      - run:
          name: Build
          command: xcodebuild -project CoNotebook.xcodeproj -scheme CoNotebook -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' clean build
      - run:
          name: Run Tests
          command: xcodebuild test -project CoNotebook.xcodeproj -scheme CoNotebook -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
