version: 2.1
jobs:
  build:
    macos:
      xcode: "13.2.1"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            gem install bundler
            bundle install
            bundle exec pod install
      - run:
          name: Build
          command: xcodebuild -workspace CoNotebook.xcworkspace -scheme CoNotebook -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' clean build
      - run:
          name: Run Tests
          command: xcodebuild test -workspace CoNotebook.xcworkspace -scheme CoNotebook -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
