# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Upload to Testflight"
  lane :upload_testflight do

    api_key = app_store_connect_api_key(
      key_id: $APPLE_KEY_ID,
      issuer_id: $APPLE_ISSUER_ID,
      key_content: $APPLE_KEY_CONTENT,
      is_key_content_base64: true,           
      duration: 1200,            
      in_house: false
    )
    increment_build_number(xcodeproj: "CoNotebook.xcodeproj")
    # Set up Distribution code signing and build the app
    match(type: "appstore",api_key: api_key)
    gym(scheme: "CoNotebook")
    # Upload the binary to TestFlight and automatically publish
    # to the configured beta testing group
    #app_store_connect_api_key
    pilot(
      distribute_external: true,
      notify_external_testers: true,
      groups: ["Beta"],
      changelog: "This is another new build from CircleCI!"
    )
  end
end
