# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Upload to Testflight"
  lane :upload_testflight do

    app_identifier = "com.corentinrobert.notebook"

    increment_build_number(
      build_number: app_store_build_number(
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "CoNotebook.xcodeproj"),
        live: false
      ) + 1,
    )

    # Set up Distribution code signing and build the app
    match(type: "appstore", app_identifier: "com.corentinrobert.notebook", readonly: true)
    gym(scheme: "CoNotebook")
    # Upload the binary to TestFlight and automatically publish
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      duration: 1200,
      in_house: false  
    )

  end
end
